"use client";

import React, { useState, useEffect, useMemo, useCallback, useRef, Suspense } from "react";
import dynamic from "next/dynamic";
import {
  ArrowLeft, Download, RotateCcw, Trash2, Film, Wand2, ImagePlus,
  Loader2, Volume2, RefreshCw, Play, Pause, Image as ImageIcon, Clapperboard,
  Save, Bookmark, BookmarkCheck, Sparkles, ChevronDown, ChevronLeft, ChevronRight, Settings, Music,
} from "lucide-react";
import { useRouter, useSearchParams } from "next/navigation";
import Sidebar from "@/components/Sidebar";
import { saveProject, getProject, toggleSaved, type Project, type ProjectStyle } from "@/lib/projectStore";
import { loadPreferences, saveSubtitlePref, saveGenerationPref, type SubtitlePreferences } from "@/lib/userPreferences";
import { buildStylePrompt, type GenerationSettings } from "@/lib/generationSettings";
import type { VideoProps, SceneData, SceneType, MotionStyleId } from "@/remotion/types";
import {
  VIDEO_FPS,
  SCENE_DURATION_FRAMES,
  TRANSITION_FRAMES,
  MOTION_STYLES,
  recommendStyle,
  getSceneDurationFrames,
} from "@/remotion/types";
import { refineForDisplay } from "@/remotion/textUtils";
import { AVAILABLE_FONTS, getFontsForLanguage } from "@/remotion/fonts";
import { apiFetch } from "@/lib/apiFetch";
import { RenderConfirmDialog } from "@/components/RenderPanel";
import { useRender } from "@/context/RenderContext";

const RemotionPlayer = dynamic(() => import("./RemotionPlayerWrapper"), {
  ssr: false,
});

function getSceneStartFrame(scenes: SceneData[], index: number): number {
  let frame = 0;
  for (let i = 0; i < index; i++) {
    const dur = getSceneDurationFrames(scenes[i], VIDEO_FPS, SCENE_DURATION_FRAMES);
    frame += dur;
    if (i < scenes.length - 1 && scenes[i].fadeEnabled === true && scenes[i + 1].fadeEnabled === true) {
      frame -= TRANSITION_FRAMES;
    }
  }
  return Math.max(0, frame);
}

interface VoiceInfo {
  voice_id: string;
  name: string;
  language: string;
  accent: string;
  preview_url: string;
  gender?: string;
  original_name?: string;
  speaker_name?: string;
  style_name?: string;
}

interface SpeakerGroup {
  name: string;
  originalName: string;
  gender: string;
  styles: { id: string; styleName: string }[];
}

function calcTotalDuration(scenes: SceneData[]) {
  if (scenes.length <= 0) return SCENE_DURATION_FRAMES;
  const total = scenes.reduce(
    (acc, s) => acc + getSceneDurationFrames(s, VIDEO_FPS, SCENE_DURATION_FRAMES),
    0,
  );
  let overlaps = 0;
  for (let i = 0; i < scenes.length - 1; i++) {
    if (scenes[i].fadeEnabled === true && scenes[i + 1].fadeEnabled === true) {
      overlaps += TRANSITION_FRAMES;
    }
  }
  return total - overlaps;
}

export default function EditorPageWrapper() {
  return (
    <Suspense fallback={<div className="flex items-center justify-center h-screen bg-ed-bg"><p className="text-ed-text-muted">로딩 중...</p></div>}>
      <EditorPage />
    </Suspense>
  );
}

function EditorPage() {
  const router = useRouter();
  const searchParams = useSearchParams();
  const { startRender, isRendering } = useRender();
  const [scenes, setScenes] = useState<SceneData[]>([]);
  const [selectedScene, setSelectedScene] = useState(0);
  const [subtitleOpen, setSubtitleOpen] = useState(false);
  const [settingsPanelOpen, setSettingsPanelOpen] = useState(false);
  const [seekFrame, setSeekFrame] = useState<number | undefined>(undefined);
  const [renderUrl, setRenderUrl] = useState<string | null>(null);
  const [confirmDialog, setConfirmDialog] = useState<{ open: boolean; props: VideoProps | null; sceneCount: number; sceneIdx: number | null }>({ open: false, props: null, sceneCount: 0, sceneIdx: null });
  const [isRefining, setIsRefining] = useState(false);
  const [generatingImageIdx, setGeneratingImageIdx] = useState<Set<number>>(new Set());
  const [generatingTTSIdx, setGeneratingTTSIdx] = useState<Set<number>>(new Set());
  const [generatingVideoIdx, setGeneratingVideoIdx] = useState<Set<number>>(new Set());
  const [generatingSfx, setGeneratingSfx] = useState(false);
  const [generatingSfxIdx, setGeneratingSfxIdx] = useState<Set<number>>(new Set());
  const [regeneratingMotionIdx, setRegeneratingMotionIdx] = useState<Set<number>>(new Set());
  const [projectStyle, setProjectStyle] = useState<ProjectStyle | null>(null);
  const sfxAutoGenerated = useRef(false);
  const [batchImageProgress, setBatchImageProgress] = useState<{ done: number; total: number } | null>(null);
  const [batchTTSProgress, setBatchTTSProgress] = useState<{ done: number; total: number } | null>(null);
  const [batchVideoProgress, setBatchVideoProgress] = useState<{ done: number; total: number } | null>(null);
  const [ttsLanguage, setTtsLanguage] = useState<"ko" | "ja">("ko");
  const [showKoTranslation, setShowKoTranslation] = useState(false);
  const [koTranslations, setKoTranslations] = useState<Record<number, string>>({});
  const [voices, setVoices] = useState<VoiceInfo[]>([]);
  const [selectedVoice, setSelectedVoice] = useState("");
  const [selectedJaSpeaker, setSelectedJaSpeaker] = useState("");
  const [playingAudio, setPlayingAudio] = useState<number | null>(null);
  const audioRef = useRef<HTMLAudioElement | null>(null);
  const [projectId, setProjectId] = useState<string | null>(null);
  const [isSaved, setIsSaved] = useState(false);
  const [mobileTab, setMobileTab] = useState<"player" | "scenes" | "settings">("player");

  const handleSaveProject = useCallback(async () => {
    if (scenes.length === 0) return;
    const title = scenes[0]?.line?.slice(0, 40) || "무제 프로젝트";
    const script = scenes.map((s) => s.line).join("\n");
    const proj = await saveProject({
      id: projectId ?? undefined,
      title,
      script,
      scenes,
      saved: isSaved,
      ...(projectStyle ? { style: projectStyle } : {}),
    });
    setProjectId(proj.id);
    sessionStorage.setItem("sourcebox-project-id", proj.id);
  }, [scenes, projectId, isSaved, projectStyle]);

  const autoSaveTimer = useRef<ReturnType<typeof setTimeout> | null>(null);
  const scenesInitialized = useRef(false);

  useEffect(() => {
    if (!scenesInitialized.current) {
      if (scenes.length > 0) scenesInitialized.current = true;
      return;
    }
    if (scenes.length === 0 || !projectId) return;
    if (autoSaveTimer.current) clearTimeout(autoSaveTimer.current);
    autoSaveTimer.current = setTimeout(() => {
      handleSaveProject();
    }, 1500);
    return () => { if (autoSaveTimer.current) clearTimeout(autoSaveTimer.current); };
  }, [scenes, projectId, handleSaveProject]);

  const handleToggleSaved = useCallback(async () => {
    if (projectId) {
      const newState = await toggleSaved(projectId);
      setIsSaved(newState);
    } else {
      await handleSaveProject();
      if (projectId) {
        const newState = await toggleSaved(projectId);
        setIsSaved(newState);
      }
    }
  }, [projectId, handleSaveProject]);

  useEffect(() => {
    (async () => {
      const storedId = sessionStorage.getItem("sourcebox-project-id");
      if (storedId) {
        setProjectId(storedId);
        const proj = await getProject(storedId);
        if (proj) {
          setIsSaved(proj.saved);

          const hasProjectStyle = proj.style && Object.values(proj.style).some((v) => v !== undefined && v !== "" && v !== null);

          if (hasProjectStyle) {
            console.log("[editor] Loaded style from project:", proj.style);
            setProjectStyle(proj.style!);
          } else {
            const genPrefs = loadPreferences().generation;
            if (genPrefs) {
              const fakeSettings = {
                artStyle: genPrefs.artStyle || "anime",
                customArtStyle: genPrefs.customArtStyle || "",
                imageModel: genPrefs.imageModel || "runware:101@1",
              } as GenerationSettings;
              const sp = buildStylePrompt(fakeSettings);
              const hasAnyPref = genPrefs.imageModel || sp || genPrefs.customStyleImage || genPrefs.characterRefImage || genPrefs.styleDescription;
              if (hasAnyPref) {
                const recoveredStyle: ProjectStyle = {
                  imageModel: genPrefs.imageModel || undefined,
                  stylePrompt: sp || undefined,
                  styleImage: genPrefs.customStyleImage || undefined,
                  characterRefImage: genPrefs.characterRefImage || undefined,
                  characterDesc: genPrefs.characterDesc || undefined,
                  styleDescription: genPrefs.styleDescription || undefined,
                };
                console.log("[editor] Recovered style from prefs:", recoveredStyle);
                setProjectStyle(recoveredStyle);
                await saveProject({ ...proj, style: recoveredStyle });
              } else {
                console.warn("[editor] No style found in project or prefs");
              }
            }
          }
        }
      }
    })();
  }, []);

  useEffect(() => {
    const savedPrefs = loadPreferences().generation;
    const lang = (savedPrefs?.language as "ko" | "ja") || "ko";
    setTtsLanguage(lang);
    const savedVoice = savedPrefs?.voiceId;

    if (lang === "ja") {
      apiFetch("/api/tts-voicevox-speakers")
        .then((r) => r.json())
        .then((d) => {
          if (d.speakers?.length) {
            const mapped = d.speakers.map((s: { speaker_id: number; name: string; gender?: string; original_name?: string; speaker_name?: string; style_name?: string }) => ({
              voice_id: String(s.speaker_id),
              name: s.name,
              language: "ja",
              accent: "",
              preview_url: "",
              gender: s.gender || "",
              original_name: s.original_name || "",
              speaker_name: s.speaker_name || s.name,
              style_name: s.style_name || "일반",
            }));
            setVoices(mapped);
            const DEFAULT_JA_VOICE = "13";
            const targetId = savedVoice || (mapped.find((v: VoiceInfo) => v.voice_id === DEFAULT_JA_VOICE)?.voice_id) || mapped[0].voice_id;
            setSelectedVoice(targetId);
            const found = mapped.find((v: VoiceInfo) => v.voice_id === targetId);
            setSelectedJaSpeaker(found?.speaker_name || found?.name || mapped[0].speaker_name || mapped[0].name);
          }
        })
        .catch(() => {});
    } else {
      apiFetch("/api/tts-voices")
        .then((r) => r.json())
        .then((d) => {
          if (d.voices?.length) {
            setVoices(d.voices);
            setSelectedVoice(savedVoice || d.voices[0].voice_id);
          }
        })
        .catch(() => {});
    }
  }, []);

  const regenerateImage = useCallback(async (sceneIndex: number, customPrompt?: string) => {
    setGeneratingImageIdx((prev) => new Set(prev).add(sceneIndex));
    try {
      const scene = scenes[sceneIndex];
      const prompt = customPrompt || scene.imagePrompt || "A detailed cinematic wide shot of a visually interesting scene with rich environment details, dynamic composition, dramatic lighting and camera angle. cinematic lighting, high quality, no text, no watermark, no typography, no letters";
      const body: Record<string, unknown> = { prompt };

      let style = projectStyle;
      if (!style || !Object.values(style).some((v) => v !== undefined && v !== "")) {
        const genPrefs = loadPreferences().generation;
        if (genPrefs && (genPrefs.imageModel || genPrefs.styleDescription || genPrefs.customStyleImage || genPrefs.characterRefImage)) {
          style = {
            imageModel: genPrefs.imageModel || undefined,
            stylePrompt: genPrefs.customArtStyle || genPrefs.artStyle || undefined,
            styleImage: genPrefs.customStyleImage || undefined,
            characterRefImage: genPrefs.characterRefImage || undefined,
            characterDesc: genPrefs.characterDesc || undefined,
            styleDescription: genPrefs.styleDescription || undefined,
          };
          setProjectStyle(style);
          console.log("[regenerateImage] Recovered style from prefs:", style);
        }
      }

      if (style) {
        if (style.imageModel) body.model = style.imageModel;
        if (style.stylePrompt) body.stylePrompt = style.stylePrompt;
        if (style.characterDesc) body.characterDesc = style.characterDesc;
        if (style.styleDescription) body.styleDescription = style.styleDescription;
        if (style.styleImage) body.styleImage = style.styleImage;
        if (style.characterRefImage) body.characterRefImage = style.characterRefImage;
      }
      console.log("[regenerateImage] style:", style, "body:", JSON.stringify(body).slice(0, 500));
      const res = await apiFetch("/api/generate-image", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify(body),
      });
      if (!res.ok) throw new Error(`API error: ${res.status}`);
      const data = await res.json();
      if (data.imageUrl) {
        setScenes((prev) => {
          const next = [...prev];
          next[sceneIndex] = {
            ...next[sceneIndex],
            backgroundImage: data.imageUrl,
            mainImage: data.imageUrl,
            mainImageSource: "AI Generated",
          };
          return next;
        });
      }
    } catch (err: unknown) {
      console.error("Image generation error:", err);
      alert(`이미지 생성 실패: ${(err as Error).message}`);
    } finally {
      setGeneratingImageIdx((prev) => { const next = new Set(prev); next.delete(sceneIndex); return next; });
    }
  }, [scenes, projectStyle]);

  const generateSfx = useCallback(async (sceneIndex: number) => {
    setGeneratingSfx(true);
    setGeneratingSfxIdx((prev) => new Set(prev).add(sceneIndex));
    try {
      const scene = scenes[sceneIndex];
      const res = await apiFetch("/api/generate-sfx", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ motionStyle: scene.motionStyle, durationSeconds: 2 }),
      });
      const data = await res.json();
      if (data.sfxUrl) {
        setScenes((prev) => prev.map((s, i) => i === sceneIndex ? { ...s, sfxUrl: data.sfxUrl } : s));
      }
    } catch (err) {
      console.error("SFX generation failed:", err);
    } finally {
      setGeneratingSfx(false);
      setGeneratingSfxIdx((prev) => { const next = new Set(prev); next.delete(sceneIndex); return next; });
    }
  }, [scenes]);

  const generateVideoClip = useCallback(async (sceneIndex: number) => {
    setGeneratingVideoIdx((prev) => new Set(prev).add(sceneIndex));
    try {
      const scene = scenes[sceneIndex];
      if (!scene.mainImage) return;
      const imgSrc = scene.mainImage.startsWith("http")
        ? scene.mainImage
        : `${window.location.origin}${scene.mainImage}`;
      const res = await apiFetch("/api/generate-video-clip", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          imageUrl: imgSrc,
          prompt: scene.imagePrompt || "cinematic camera movement, smooth animation",
          durationSeconds: scene.audioDuration || 6,
        }),
      });
      if (!res.ok) throw new Error(`API error: ${res.status}`);
      const data = await res.json();
      if (data.videoUrl) {
        setScenes((prev) => {
          const next = [...prev];
          next[sceneIndex] = { ...next[sceneIndex], videoClipUrl: data.videoUrl };
          return next;
        });
      }
    } catch (err: unknown) {
      console.error("Video clip generation error:", err);
    } finally {
      setGeneratingVideoIdx((prev) => { const s = new Set(prev); s.delete(sceneIndex); return s; });
    }
  }, [scenes]);

  const batchGenerateVideoClips = useCallback(async () => {
    const targets = scenes
      .map((s, i) => (s.sceneType === "image" && s.mainImage && !s.videoClipUrl ? i : -1))
      .filter((i) => i >= 0);
    if (targets.length === 0) return;
    setBatchVideoProgress({ done: 0, total: targets.length });

    const fns = targets.map((idx) => async () => {
      const scene = scenes[idx];
      const imgSrc = scene.mainImage.startsWith("http") ? scene.mainImage : `${window.location.origin}${scene.mainImage}`;
      setGeneratingVideoIdx((prev) => new Set(prev).add(idx));
      try {
        const res = await apiFetch("/api/generate-video-clip", {
          method: "POST",
          headers: { "Content-Type": "application/json" },
          body: JSON.stringify({
            imageUrl: imgSrc,
            prompt: scene.imagePrompt || "cinematic camera movement, smooth animation",
            durationSeconds: scene.audioDuration || 6,
          }),
        });
        if (!res.ok) return null;
        const data = await res.json();
        return { idx, videoUrl: data.videoUrl as string };
      } catch {
        return null;
      } finally {
        setGeneratingVideoIdx((prev) => { const s = new Set(prev); s.delete(idx); return s; });
        setBatchVideoProgress((prev) => prev ? { ...prev, done: prev.done + 1 } : null);
      }
    });

    const limit = 3;
    const results: PromiseSettledResult<{ idx: number; videoUrl: string } | null>[] = new Array(fns.length);
    let nextIdx = 0;
    async function worker() {
      while (nextIdx < fns.length) {
        const i = nextIdx++;
        try { results[i] = { status: "fulfilled", value: await fns[i]() }; }
        catch (e) { results[i] = { status: "rejected", reason: e }; }
      }
    }
    await Promise.all(Array.from({ length: Math.min(limit, fns.length) }, () => worker()));

    setScenes((prev) => {
      const next = [...prev];
      for (const r of results) {
        if (r.status === "fulfilled" && r.value?.videoUrl) {
          next[r.value.idx] = { ...next[r.value.idx], videoClipUrl: r.value.videoUrl };
        }
      }
      return next;
    });
    setBatchVideoProgress(null);
  }, [scenes]);

  const removeVideoClip = useCallback((sceneIndex: number) => {
    setScenes((prev) => {
      const next = [...prev];
      next[sceneIndex] = { ...next[sceneIndex], videoClipUrl: undefined };
      return next;
    });
  }, []);

  const batchRegenerateImages = useCallback(async () => {
    let style = projectStyle;
    if (!style || !Object.values(style).some((v) => v !== undefined && v !== "")) {
      const genPrefs = loadPreferences().generation;
      if (genPrefs && (genPrefs.imageModel || genPrefs.styleDescription || genPrefs.customStyleImage || genPrefs.characterRefImage)) {
        style = {
          imageModel: genPrefs.imageModel || undefined,
          stylePrompt: genPrefs.customArtStyle || genPrefs.artStyle || undefined,
          styleImage: genPrefs.customStyleImage || undefined,
          characterRefImage: genPrefs.characterRefImage || undefined,
          characterDesc: genPrefs.characterDesc || undefined,
          styleDescription: genPrefs.styleDescription || undefined,
        };
        setProjectStyle(style);
      }
    }

    const total = scenes.length;
    setBatchImageProgress({ done: 0, total });
    for (let i = 0; i < total; i++) {
      const scene = scenes[i];
      const prompt = scene.imagePrompt || "A detailed cinematic wide shot of a visually interesting scene with rich environment details, dynamic composition, dramatic lighting and camera angle. cinematic lighting, high quality, no text, no watermark, no typography, no letters";
      const reqBody: Record<string, unknown> = { prompt };
      if (style) {
        if (style.imageModel) reqBody.model = style.imageModel;
        if (style.stylePrompt) reqBody.stylePrompt = style.stylePrompt;
        if (style.characterDesc) reqBody.characterDesc = style.characterDesc;
        if (style.styleDescription) reqBody.styleDescription = style.styleDescription;
        if (style.styleImage) reqBody.styleImage = style.styleImage;
        if (style.characterRefImage) reqBody.characterRefImage = style.characterRefImage;
      }
      try {
        const res = await apiFetch("/api/generate-image", {
          method: "POST",
          headers: { "Content-Type": "application/json" },
          body: JSON.stringify(reqBody),
        });
        if (res.ok) {
          const data = await res.json();
          if (data.imageUrl) {
            setScenes((prev) => prev.map((s, idx) =>
              idx === i ? { ...s, backgroundImage: data.imageUrl, mainImage: data.imageUrl, mainImageSource: "AI Generated" } : s
            ));
          }
        }
      } catch { /* skip */ }
      setBatchImageProgress({ done: i + 1, total });
    }
    setBatchImageProgress(null);
  }, [scenes, projectStyle]);

  const jaSpeakerGroups: SpeakerGroup[] = useMemo(() => {
    if (ttsLanguage !== "ja" || voices.length === 0) return [];
    const groupMap = new Map<string, SpeakerGroup>();
    for (const v of voices) {
      const key = v.speaker_name || v.name;
      if (!groupMap.has(key)) {
        groupMap.set(key, {
          name: key,
          originalName: v.original_name?.replace(/ \(.*\)$/, "") || key,
          gender: v.gender || "",
          styles: [],
        });
      }
      groupMap.get(key)!.styles.push({ id: v.voice_id, styleName: v.style_name || "일반" });
    }
    const genderOrder: Record<string, number> = { "남": 0, "중성": 1, "여": 2 };
    return Array.from(groupMap.values()).sort(
      (a, b) => (genderOrder[a.gender] ?? 3) - (genderOrder[b.gender] ?? 3),
    );
  }, [voices, ttsLanguage]);

  const fetchTranslations = useCallback(async () => {
    const untranslated = scenes.map((s, i) => ({ i, text: s.line })).filter(({ i }) => !koTranslations[i]);
    if (untranslated.length === 0) return;
    try {
      const BATCH = 50;
      for (let b = 0; b < untranslated.length; b += BATCH) {
        const batch = untranslated.slice(b, b + BATCH);
        const res = await apiFetch("/api/translate", {
          method: "POST",
          headers: { "Content-Type": "application/json" },
          body: JSON.stringify({ texts: batch.map(u => u.text), from: "ja", to: "ko" }),
        });
        const data = await res.json();
        if (data.translations) {
          setKoTranslations(prev => {
            const next = { ...prev };
            batch.forEach((u, idx) => { if (data.translations[idx]) next[u.i] = data.translations[idx]; });
            return next;
          });
        }
      }
    } catch (err) {
      console.error("Translation failed:", err);
    }
  }, [scenes, koTranslations]);

  const callTTS = useCallback(async (text: string) => {
    const endpoint = ttsLanguage === "ja" ? "/api/tts-voicevox" : "/api/tts";
    const body = ttsLanguage === "ja"
      ? { text, speakerId: selectedVoice ? Number(selectedVoice) : undefined }
      : { text, voiceId: selectedVoice || undefined };
    const res = await apiFetch(endpoint, {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify(body),
    });
    if (!res.ok) throw new Error(`TTS error: ${res.status}`);
    return await res.json() as { audioUrl: string; duration: number };
  }, [ttsLanguage, selectedVoice]);

  const batchRegenerateTTS = useCallback(async () => {
    const total = scenes.length;
    setBatchTTSProgress({ done: 0, total });
    for (let i = 0; i < total; i++) {
      const scene = scenes[i];
      const text = scene.narration || scene.line;
      try {
        const data = await callTTS(text);
        setScenes((prev) => prev.map((s, idx) =>
          idx === i ? { ...s, audioUrl: data.audioUrl, audioDuration: data.duration } : s
        ));
      } catch { /* skip */ }
      setBatchTTSProgress({ done: i + 1, total });
    }
    setBatchTTSProgress(null);
  }, [scenes, callTTS]);

  const regenerateTTS = useCallback(async (sceneIndex: number) => {
    setGeneratingTTSIdx((prev) => new Set(prev).add(sceneIndex));
    try {
      const scene = scenes[sceneIndex];
      const text = scene.narration || scene.line;
      const data = await callTTS(text);
      setScenes((prev) => {
        const next = [...prev];
        next[sceneIndex] = {
          ...next[sceneIndex],
          audioUrl: data.audioUrl,
          audioDuration: data.duration,
        };
        return next;
      });
    } catch (err: unknown) {
      console.error("TTS error:", err);
      alert(`TTS 생성 실패: ${(err as Error).message}`);
    } finally {
      setGeneratingTTSIdx((prev) => { const next = new Set(prev); next.delete(sceneIndex); return next; });
    }
  }, [scenes, callTTS]);

  const regenerateMotionData = useCallback(async (sceneIndex: number) => {
    setRegeneratingMotionIdx((prev) => new Set(prev).add(sceneIndex));
    try {
      const scene = scenes[sceneIndex];
      const res = await apiFetch("/api/analyze-scenes", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          scenes: [{
            line: scene.narration || scene.line,
            keywords: scene.keywords || [],
            suggestedStyle: scene.motionStyle,
            sceneType: scene.sceneType,
          }],
          language: ttsLanguage === "ja" ? "ja" : undefined,
        }),
      });
      if (!res.ok) throw new Error(`API error: ${res.status}`);
      const data = await res.json();
      const result = data.results?.[0];
      if (result) {
        setScenes((prev) => prev.map((s, i) => {
          if (i !== sceneIndex) return s;
          return {
            ...s,
            ...(result.motionStyle && { motionStyle: result.motionStyle as MotionStyleId }),
            ...(result.displayText && { displayText: result.displayText }),
            ...(result.sourceLabel !== undefined && { sourceLabel: result.sourceLabel }),
            ...(result.infographicData && { infographicData: result.infographicData as any }),
            ...(result.highlightKeywords?.length && { keywords: result.highlightKeywords }),
          };
        }));
      }
    } catch (err: unknown) {
      console.error("Motion regeneration error:", err);
      alert(`모션 재생성 실패: ${(err as Error).message}`);
    } finally {
      setRegeneratingMotionIdx((prev) => { const next = new Set(prev); next.delete(sceneIndex); return next; });
    }
  }, [scenes, ttsLanguage]);

  const playAudioPreview = useCallback((sceneIndex: number) => {
    const scene = scenes[sceneIndex];
    if (!scene.audioUrl) return;

    if (playingAudio === sceneIndex && audioRef.current) {
      audioRef.current.pause();
      audioRef.current = null;
      setPlayingAudio(null);
      return;
    }

    if (audioRef.current) {
      audioRef.current.pause();
    }

    const audio = new Audio(scene.audioUrl);
    audioRef.current = audio;
    setPlayingAudio(sceneIndex);
    audio.play();
    audio.onended = () => {
      setPlayingAudio(null);
      audioRef.current = null;
    };
  }, [scenes, playingAudio]);

  const refineWithAI = useCallback(async (targetScenes: SceneData[], indices?: number[]) => {
    setIsRefining(true);
    try {
      const toRefine = indices ? indices.map((i) => targetScenes[i]) : targetScenes;
      const res = await apiFetch("/api/refine-text", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          scenes: toRefine.map((s) => ({
            line: s.line,
            keywords: s.keywords,
            motionStyle: s.motionStyle,
          })),
        }),
      });
      if (!res.ok) throw new Error(`API error: ${res.status}`);
      const data = await res.json();
      const results = data.results as {
        displayText: string;
        subText: string;
        highlightKeywords: string[];
      }[];
      setScenes((prev) => {
        const next = [...prev];
        const targetIndices = indices ?? prev.map((_, i) => i);
        targetIndices.forEach((idx, ri) => {
          if (results[ri]) {
            next[idx] = {
              ...next[idx],
              displayText: results[ri].displayText,
              subText: results[ri].subText,
              keywords: results[ri].highlightKeywords.length > 0
                ? results[ri].highlightKeywords
                : next[idx].keywords,
            };
          }
        });
        return next;
      });
    } catch (err: unknown) {
      console.error("AI refine error:", err);
      alert(`문구 생성 실패: ${(err as Error).message}`);
    } finally {
      setIsRefining(false);
    }
  }, []);

  const seekToScene = useCallback((index: number) => {
    setSelectedScene(index);
    const frame = getSceneStartFrame(scenes, index);
    setSeekFrame(frame);
  }, [scenes]);

  const autoGenerateSfx = useCallback((index: number, motionStyle?: string) => {
    apiFetch("/api/generate-sfx", {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({ motionStyle: motionStyle || "quote", durationSeconds: 2 }),
    })
      .then((r) => r.json())
      .then((data) => {
        if (data.sfxUrl) {
          setScenes((p) => p.map((s, i) => i === index ? { ...s, sfxUrl: data.sfxUrl } : s));
        }
      })
      .catch(() => {});
  }, []);

  const toggleSceneType = useCallback((index: number) => {
    let switchedToMotion = false;
    let motionStyle: string | undefined;
    setScenes((prev) => {
      const next = [...prev];
      const current = next[index];
      const newType: SceneType = current.sceneType === "motion" ? "image" : "motion";
      next[index] = {
        ...current,
        sceneType: newType,
        zoom: newType === "image" ? (current.zoom ?? "in") : undefined,
      };
      if (newType === "motion" && !current.sfxUrl) {
        switchedToMotion = true;
        motionStyle = current.motionStyle;
      }
      return next;
    });
    if (switchedToMotion) {
      autoGenerateSfx(index, motionStyle);
    }
  }, [autoGenerateSfx]);

  useEffect(() => {
    const savedSubPrefs = loadPreferences().subtitle || {};
    const applySubtitleDefaults = (scenesArr: SceneData[]): SceneData[] =>
      scenesArr.map((s) => ({
        ...s,
        subtitleSize: s.subtitleSize ?? savedSubPrefs.subtitleSize,
        subtitleFont: s.subtitleFont ?? savedSubPrefs.subtitleFont,
        subtitleColor: s.subtitleColor ?? savedSubPrefs.subtitleColor,
        subtitleBg: s.subtitleBg ?? savedSubPrefs.subtitleBg,
        subtitleStroke: s.subtitleStroke ?? savedSubPrefs.subtitleStroke,
        subtitleStrokeWidth: s.subtitleStrokeWidth ?? savedSubPrefs.subtitleStrokeWidth,
        subtitleX: s.subtitleX ?? savedSubPrefs.subtitleX,
        subtitleY: s.subtitleY ?? savedSubPrefs.subtitleY,
      }));

    const raw = searchParams.get("data");
    if (raw) {
      try {
        setScenes(applySubtitleDefaults(JSON.parse(decodeURIComponent(raw))));
        return;
      } catch { /* ignore */ }
    }

    const storedId = sessionStorage.getItem("sourcebox-project-id");
    if (storedId) {
      getProject(storedId).then((proj) => {
        if (proj?.scenes?.length) {
          setScenes(applySubtitleDefaults(proj.scenes));
          return;
        }
        loadFromSessionOrDefault();
      });
      return;
    }

    loadFromSessionOrDefault();

    function loadFromSessionOrDefault() {
    const stored = sessionStorage.getItem("sourcebox-scenes");
    if (stored) {
      try {
        const parsed = JSON.parse(stored);
        if (parsed.length > 0) { setScenes(applySubtitleDefaults(parsed)); return; }
      } catch { /* ignore */ }
    }

    setScenes([
      {
        line: "2024년 공식 통계 기준으로는 서울 자가 아파트 가격이 연소득의 약 14배 수준이에요.",
        keywords: ["14배", "서울", "아파트"],
        backgroundImage: "",
        mainImage: "",
        mainImageSource: "",
        type: "stock-image",
        sceneType: "motion",
        motionStyle: "bigStat",
        narration: "2024년 공식 통계 기준으로는 서울 자가 아파트 가격이 연소득의 약 14배 수준이에요.",
        infographicData: { layout: "bigStat", category: "PIR 지수 2024", number: "14", unit: "배", description: "서울 아파트 가격 대비 연소득" },
      },
      {
        line: "밈, 스톡, 구글 이미지를 활용한 영상 제작",
        keywords: ["밈", "스톡"],
        backgroundImage: "",
        mainImage: "",
        mainImageSource: "",
        type: "meme",
        sceneType: "image",
        motionStyle: "quote",
        narration: "밈, 스톡, 구글 이미지를 활용한 영상 제작",
        zoom: "in",
      },
    ]);
    }
  }, [searchParams]);

  const jaAutoTranslated = useRef(false);
  useEffect(() => {
    if (jaAutoTranslated.current || scenes.length === 0 || ttsLanguage !== "ja") return;
    jaAutoTranslated.current = true;
    setShowKoTranslation(true);
    fetchTranslations();
  }, [scenes, ttsLanguage, fetchTranslations]);

  useEffect(() => {
    if (sfxAutoGenerated.current || scenes.length === 0) return;
    const motionWithoutSfx = scenes
      .map((s, i) => ({ s, i }))
      .filter(({ s }) => s.sceneType === "motion" && !s.sfxUrl);
    if (motionWithoutSfx.length === 0) return;
    sfxAutoGenerated.current = true;

    for (const { s, i } of motionWithoutSfx) {
      autoGenerateSfx(i, s.motionStyle);
    }
  }, [scenes, autoGenerateSfx]);

  const videoProps: VideoProps = useMemo(
    () => ({
      scenes,
      fps: VIDEO_FPS,
      sceneDurationFrames: SCENE_DURATION_FRAMES,
    }),
    [scenes],
  );

  const totalFrames = useMemo(() => calcTotalDuration(scenes), [scenes]);

  const SUBTITLE_KEYS: (keyof SubtitlePreferences)[] = [
    "subtitleSize", "subtitleFont", "subtitleColor", "subtitleBg",
    "subtitleStroke", "subtitleStrokeWidth", "subtitleX", "subtitleY",
  ];

  const updateScene = useCallback((index: number, updates: Partial<SceneData>) => {
    setScenes((prev) =>
      prev.map((s, i) => (i === index ? { ...s, ...updates } : s)),
    );
    const subtitleUpdates: Partial<SubtitlePreferences> = {};
    for (const key of SUBTITLE_KEYS) {
      if (key in updates) {
        (subtitleUpdates as Record<string, unknown>)[key] = (updates as Record<string, unknown>)[key];
      }
    }
    if (Object.keys(subtitleUpdates).length > 0) {
      saveSubtitlePref(subtitleUpdates);
    }
  }, []);

  const removeScene = useCallback((index: number) => {
    setScenes((prev) => prev.filter((_, i) => i !== index));
    setSelectedScene((prev) => Math.max(0, prev - 1));
  }, []);

  const estimateRenderSeconds = useCallback((sceneCount: number) => {
    return Math.max(60, sceneCount * 8);
  }, []);

  const handleExportAll = useCallback(() => {
    setConfirmDialog({ open: true, props: videoProps, sceneCount: scenes.length, sceneIdx: null });
  }, [videoProps, scenes.length]);

  const handleExportScene = useCallback((index: number) => {
    const props = { scenes: [scenes[index]], fps: VIDEO_FPS, sceneDurationFrames: SCENE_DURATION_FRAMES };
    setConfirmDialog({ open: true, props, sceneCount: 1, sceneIdx: index });
  }, [scenes]);

  const handleConfirmRender = useCallback(() => {
    if (confirmDialog.props) {
      const sceneIdx = confirmDialog.sceneIdx;
      const label = sceneIdx !== null
        ? `장면 ${sceneIdx + 1} 내보내기`
        : `전체 영상 내보내기 (${confirmDialog.props.scenes.length}장면)`;
      startRender(confirmDialog.props, label, projectId || undefined);
    }
    setConfirmDialog({ open: false, props: null, sceneCount: 0, sceneIdx: null });
  }, [confirmDialog, startRender, projectId]);

  const handleCancelRender = useCallback(() => {
    setConfirmDialog({ open: false, props: null, sceneCount: 0, sceneIdx: null });
  }, []);

  if (scenes.length === 0) {
    return (
      <div className="flex items-center justify-center h-screen bg-ed-bg-deep">
        <div className="text-center text-ed-text">
          <p className="text-lg mb-4">장면 데이터가 없습니다</p>
          <button onClick={() => router.push("/")} className="px-4 py-2 bg-accent text-white rounded-xl hover:bg-accent/90">
            돌아가기
          </button>
        </div>
      </div>
    );
  }

  const currentScene = scenes[selectedScene];
  const motionCount = scenes.filter((s) => s.sceneType === "motion").length;
  const imageCount = scenes.filter((s) => s.sceneType === "image").length;

  return (
    <div className="flex h-[100dvh] bg-ed-bg text-ed-text">
      <Sidebar />
      <div className="flex flex-col flex-1 min-w-0 pb-14 md:pb-0">
      {/* Header */}
      <header className="flex items-center justify-between px-3 md:px-5 py-2 md:py-2.5 border-b border-ed-border bg-ed-bg-deep shrink-0">
        <div className="flex items-center gap-2 md:gap-3 min-w-0">
          <button onClick={() => router.push("/")} className="p-1.5 rounded-lg hover:bg-ed-surface-active transition-colors shrink-0">
            <ArrowLeft size={16} />
          </button>
          <h1 className="text-sm font-semibold shrink-0">에디터</h1>
          <span className="text-[11px] text-ed-text-dim truncate hidden sm:inline">
            {scenes.length}장면 · 모션 {motionCount} · 이미지 {imageCount} · {(totalFrames / VIDEO_FPS).toFixed(1)}초
          </span>
        </div>

        <div className="flex items-center gap-1 md:gap-1.5 shrink-0">
          <button
            onClick={handleSaveProject}
            className="flex items-center gap-1 px-2 md:px-2.5 py-1.5 text-[11px] bg-ed-surface-active text-ed-text-muted rounded-lg hover:bg-ed-surface-hover transition-colors"
          >
            <Save size={12} />
            <span className="hidden sm:inline">저장</span>
          </button>
          <button
            onClick={handleToggleSaved}
            className="p-1.5 rounded-lg hover:bg-ed-surface-active transition-colors"
            title={isSaved ? "북마크 해제" : "북마크"}
          >
            {isSaved ? <BookmarkCheck size={14} className="text-accent" /> : <Bookmark size={14} className="text-ed-text-dim" />}
          </button>
          {renderUrl && (
            <a href={renderUrl} download className="flex items-center gap-1 px-2 md:px-2.5 py-1.5 text-[11px] bg-green-600 text-white rounded-lg hover:bg-green-500 transition-colors shrink-0">
              <Download size={12} />
              <span className="hidden sm:inline">다운로드</span>
            </a>
          )}
          <button
            onClick={handleExportAll}
            disabled={isRendering}
            className="flex items-center gap-1 md:gap-1.5 px-2 md:px-3 py-1.5 text-[11px] font-medium bg-accent text-white rounded-lg hover:bg-accent/90 transition-colors disabled:opacity-50"
          >
            {isRendering ? (
              <><RotateCcw size={12} className="animate-spin" /> 렌더링 중</>
            ) : (
              <><Download size={12} /> <span className="hidden sm:inline">내보내기</span></>
            )}
          </button>
        </div>
      </header>

      {/* Mobile tab bar */}
      <div className="md:hidden flex items-center border-b border-ed-border bg-ed-bg-deep shrink-0">
        {([
          { id: "player" as const, label: "미리보기", icon: Play },
          { id: "scenes" as const, label: "장면", icon: Film },
          { id: "settings" as const, label: "설정", icon: Settings },
        ]).map((tab) => (
          <button key={tab.id} onClick={() => setMobileTab(tab.id)}
            className={`flex-1 flex items-center justify-center gap-1.5 py-2.5 text-xs font-medium transition-colors ${mobileTab === tab.id ? "text-accent border-b-2 border-accent" : "text-ed-text-dim"}`}>
            <tab.icon size={14} />
            {tab.label}
          </button>
        ))}
      </div>

      <div className="flex flex-1 overflow-hidden">

        {/* ═══ LEFT: Video Player + Controls ═══ */}
        <div className={`${mobileTab === "player" ? "flex" : "hidden"} md:flex ${settingsPanelOpen ? "md:w-[52%]" : "md:w-[64%]"} w-full flex-col bg-ed-bg-deep md:border-r border-ed-border transition-all duration-300`}>
          <div className="flex-1 flex items-center justify-center p-4 min-h-0">
            <div className="w-full">
              <RemotionPlayer
                videoProps={videoProps}
                totalFrames={totalFrames}
                seekToFrame={seekFrame}
              />
            </div>
          </div>
          <div className="shrink-0 px-3 md:px-4 py-2 md:py-3 border-t border-ed-border space-y-2">
            {/* Voice selector */}
            <div className="flex items-center gap-1.5 md:gap-2 flex-wrap">
              <span className="text-[10px] text-ed-text-dim shrink-0">보이스</span>
              {voices.length > 0 && (
                ttsLanguage === "ja" && jaSpeakerGroups.length > 0 ? (
                  <>
                    <select
                      value={selectedJaSpeaker}
                      onChange={(e) => {
                        const spk = e.target.value;
                        setSelectedJaSpeaker(spk);
                        const group = jaSpeakerGroups.find((g) => g.name === spk);
                        if (group?.styles.length) {
                          setSelectedVoice(group.styles[0].id);
                          saveGenerationPref("voiceId", group.styles[0].id);
                        }
                      }}
                      className="text-[10px] bg-ed-surface border border-ed-border rounded-lg px-2 py-1 text-ed-text-muted focus:outline-none min-w-0"
                    >
                      {jaSpeakerGroups.map((g) => (
                        <option key={g.name} value={g.name}>[{g.gender}] {g.name} ({g.originalName})</option>
                      ))}
                    </select>
                    <select
                      value={selectedVoice}
                      onChange={(e) => { setSelectedVoice(e.target.value); saveGenerationPref("voiceId", e.target.value); }}
                      className="text-[10px] bg-ed-surface border border-ed-border rounded-lg px-2 py-1 text-ed-text-muted focus:outline-none w-[70px]"
                    >
                      {(jaSpeakerGroups.find((g) => g.name === selectedJaSpeaker)?.styles || []).map((st) => (
                        <option key={st.id} value={st.id}>{st.styleName}</option>
                      ))}
                    </select>
                    <button
                      onClick={async () => {
                        const v = voices.find((x) => x.voice_id === selectedVoice);
                        if (!v) return;
                        if (v.preview_url) { new Audio(v.preview_url).play(); return; }
                        try {
                          const res = await apiFetch(`/api/tts-voicevox-preview?id=${v.voice_id}`);
                          const d = await res.json();
                          if (d.previewUrl) { new Audio(d.previewUrl).play(); setVoices((prev) => prev.map((x) => x.voice_id === v.voice_id ? { ...x, preview_url: d.previewUrl } : x)); }
                        } catch { /* ignore */ }
                      }}
                      className="text-[10px] bg-ed-surface border border-ed-border rounded-lg px-1.5 py-1 text-ed-text-dim hover:text-ed-text-muted hover:bg-ed-surface-active transition-all shrink-0"
                      title="미리듣기"
                    >▶</button>
                  </>
                ) : (
                  <>
                    <select
                      value={selectedVoice}
                      onChange={(e) => { setSelectedVoice(e.target.value); saveGenerationPref("voiceId", e.target.value); }}
                      className="text-[10px] bg-ed-surface border border-ed-border rounded-lg px-2 py-1 text-ed-text-muted focus:outline-none"
                    >
                      {voices.map((v) => (
                        <option key={v.voice_id} value={v.voice_id}>{v.name}</option>
                      ))}
                    </select>
                    {voices.find((v) => v.voice_id === selectedVoice)?.preview_url && (
                      <button
                        onClick={() => { const v = voices.find((x) => x.voice_id === selectedVoice); if (v?.preview_url) new Audio(v.preview_url).play(); }}
                        className="text-[10px] bg-ed-surface border border-ed-border rounded-lg px-1.5 py-1 text-ed-text-dim hover:text-ed-text-muted hover:bg-ed-surface-active transition-all"
                      >▶</button>
                    )}
                  </>
                )
              )}
            </div>
            {/* Batch actions */}
            <div className="flex items-center gap-1 md:gap-1.5 flex-wrap overflow-x-auto scrollbar-hide">
              <button onClick={() => refineWithAI(scenes)} disabled={isRefining || scenes.length === 0}
                className="flex items-center gap-1 px-2 py-1.5 text-[10px] bg-purple-600/80 text-white rounded-lg hover:bg-purple-500/80 transition-colors disabled:opacity-40">
                <Wand2 size={11} className={isRefining ? "animate-spin" : ""} />
                {isRefining ? "생성 중…" : "AI 문구"}
              </button>
              <button onClick={batchRegenerateImages} disabled={!!batchImageProgress}
                className="flex items-center gap-1 px-2 py-1.5 text-[10px] bg-blue-600/80 text-white rounded-lg hover:bg-blue-500/80 transition-colors disabled:opacity-40">
                {batchImageProgress ? <><Loader2 size={11} className="animate-spin" /> {batchImageProgress.done}/{batchImageProgress.total}</> : <><ImagePlus size={11} /> 이미지 일괄</>}
              </button>
              <button onClick={batchRegenerateTTS} disabled={!!batchTTSProgress}
                className="flex items-center gap-1 px-2 py-1.5 text-[10px] bg-green-600/80 text-white rounded-lg hover:bg-green-500/80 transition-colors disabled:opacity-40">
                {batchTTSProgress ? <><Loader2 size={11} className="animate-spin" /> {batchTTSProgress.done}/{batchTTSProgress.total}</> : <><Volume2 size={11} /> TTS 일괄</>}
              </button>
              <button onClick={batchGenerateVideoClips} disabled={!!batchVideoProgress}
                className="flex items-center gap-1 px-2 py-1.5 text-[10px] bg-purple-600/80 text-white rounded-lg hover:bg-purple-500/80 transition-colors disabled:opacity-40">
                {batchVideoProgress ? <><Loader2 size={11} className="animate-spin" /> {batchVideoProgress.done}/{batchVideoProgress.total}</> : <><Film size={11} /> 영상 일괄</>}
              </button>
            </div>
          </div>
        </div>

        {/* ═══ CENTER: Scene List ═══ */}
        <div className={`${mobileTab === "scenes" ? "flex" : "hidden"} md:flex ${settingsPanelOpen ? "md:w-[24%]" : "md:w-[33%]"} w-full flex-col bg-ed-bg md:border-r border-ed-border transition-all duration-300`}>
          <div className="px-3 py-2.5 border-b border-ed-border shrink-0 flex items-center justify-between">
            <h2 className="text-[11px] font-semibold text-ed-text-muted uppercase tracking-wider">장면 목록</h2>
            {ttsLanguage === "ja" && (
              <label className="flex items-center gap-1.5 cursor-pointer select-none">
                <input
                  type="checkbox"
                  checked={showKoTranslation}
                  onChange={(e) => {
                    setShowKoTranslation(e.target.checked);
                    if (e.target.checked) fetchTranslations();
                  }}
                  className="w-3.5 h-3.5 rounded accent-accent"
                />
                <span className="text-[10px] text-ed-text-dim">한국어 번역</span>
              </label>
            )}
          </div>
          <div className="flex-1 overflow-y-auto scrollbar-hide min-h-0 p-2.5 space-y-1.5">
            {scenes.map((scene, i) => {
              const isMotion = scene.sceneType === "motion";
              const dur = getSceneDurationFrames(scene, VIDEO_FPS, SCENE_DURATION_FRAMES);
              return (
                <div
                  key={i}
                  onClick={() => seekToScene(i)}
                  className={`group relative p-3 rounded-xl cursor-pointer transition-all ${
                    selectedScene === i
                      ? "bg-ed-surface-active ring-1 ring-accent"
                      : "bg-ed-surface hover:bg-ed-surface-hover"
                  }`}
                >
                  <div className="flex items-start gap-2.5">
                    <span className={`shrink-0 w-6 h-6 rounded-md text-white text-xs font-bold flex items-center justify-center mt-0.5 select-none ${
                      isMotion ? "bg-accent/80" : "bg-blue-500/80"
                    }`}>
                      {i + 1}
                    </span>
                    <div className="flex-1 min-w-0">
                      <p className={`text-[13px] leading-relaxed ${
                        selectedScene === i ? "text-ed-text" : "text-ed-text-muted line-clamp-3"
                      }`}>
                        {scene.line}
                      </p>
                      {showKoTranslation && koTranslations[i] && (
                        <p className="text-[11px] text-blue-400/80 mt-1 line-clamp-3 leading-relaxed">
                          🇰🇷 {koTranslations[i]}
                        </p>
                      )}
                      {scene.displayText && (
                        <p className="text-[11px] text-accent/70 mt-1 line-clamp-2">
                          → {scene.displayText.replace(/\n/g, " ")}
                        </p>
                      )}
                      <div className="flex items-center gap-1.5 mt-2 flex-wrap">
                        <span className={`px-1.5 py-0.5 rounded text-[10px] font-medium ${
                          isMotion
                            ? "bg-accent/20 text-accent"
                            : "bg-blue-500/20 text-blue-400"
                        }`}>
                          {isMotion ? "🎬 모션" : scene.videoClipUrl ? "🎥 영상" : "🖼 이미지"}
                        </span>
                        {isMotion && (
                          <span className="px-1.5 py-0.5 rounded text-[10px] bg-ed-surface-active text-ed-text-muted">
                            {MOTION_STYLES.find((s) => s.id === scene.motionStyle)?.icon ?? "❝"}{" "}
                            {MOTION_STYLES.find((s) => s.id === scene.motionStyle)?.label ?? "인용문"}
                          </span>
                        )}
                        {scene.audioUrl && (
                          <span className="px-1.5 py-0.5 rounded text-[10px] bg-green-500/20 text-green-400">
                            🔊 {scene.audioDuration ? `${scene.audioDuration.toFixed(1)}s` : "TTS"}
                          </span>
                        )}
                        <span className="px-1.5 py-0.5 rounded text-[10px] bg-ed-surface text-ed-text-dim">
                          {(dur / VIDEO_FPS).toFixed(1)}초
                        </span>
                      </div>
                    </div>
                  </div>
                  {/* Action buttons row */}
                  <div className="flex items-center gap-1 mt-2 pt-2 border-t border-ed-surface">
                    <button
                      onClick={(e) => { e.stopPropagation(); regenerateImage(i); }}
                      disabled={generatingImageIdx.has(i)}
                      className="flex items-center gap-1 px-2 py-1 rounded-md text-[10px] bg-blue-500/10 text-blue-400 hover:bg-blue-500/20 transition-all disabled:opacity-30"
                    >
                      {generatingImageIdx.has(i) ? <Loader2 size={11} className="animate-spin" /> : <ImageIcon size={11} />} 이미지
                    </button>
                    <button
                      onClick={(e) => { e.stopPropagation(); regenerateTTS(i); }}
                      disabled={generatingTTSIdx.has(i)}
                      className="flex items-center gap-1 px-2 py-1 rounded-md text-[10px] bg-green-500/10 text-green-400 hover:bg-green-500/20 transition-all disabled:opacity-30"
                    >
                      {generatingTTSIdx.has(i) ? <Loader2 size={11} className="animate-spin" /> : <Volume2 size={11} />} TTS
                    </button>
                    {scene.sceneType === "motion" && (
                      <>
                        <button
                          onClick={(e) => { e.stopPropagation(); regenerateMotionData(i); }}
                          disabled={regeneratingMotionIdx.has(i)}
                          className="flex items-center gap-1 px-2 py-1 rounded-md text-[10px] bg-accent/10 text-accent hover:bg-accent/20 transition-all disabled:opacity-30"
                        >
                          {regeneratingMotionIdx.has(i) ? <Loader2 size={11} className="animate-spin" /> : <Wand2 size={11} />} 모션
                        </button>
                        <button
                          onClick={(e) => { e.stopPropagation(); scene.sfxUrl ? updateScene(i, { sfxUrl: undefined, sfxVolume: undefined }) : generateSfx(i); }}
                          disabled={generatingSfxIdx.has(i)}
                          className={`flex items-center gap-1 px-2 py-1 rounded-md text-[10px] transition-all disabled:opacity-30 ${
                            scene.sfxUrl
                              ? "bg-purple-500/20 text-purple-400 hover:bg-purple-500/30"
                              : "bg-purple-500/10 text-purple-400/70 hover:bg-purple-500/20"
                          }`}
                        >
                          {generatingSfxIdx.has(i) ? <Loader2 size={11} className="animate-spin" /> : <Music size={11} />}
                          {scene.sfxUrl ? "SFX제거" : "SFX생성"}
                        </button>
                      </>
                    )}
                    {scene.sceneType === "image" && (
                      <button
                        onClick={(e) => { e.stopPropagation(); scene.videoClipUrl ? removeVideoClip(i) : generateVideoClip(i); }}
                        disabled={generatingVideoIdx.has(i)}
                        className={`flex items-center gap-1 px-2 py-1 rounded-md text-[10px] transition-all disabled:opacity-30 ${
                          scene.videoClipUrl
                            ? "bg-purple-500/20 text-purple-400 hover:bg-purple-500/30"
                            : "bg-purple-500/10 text-purple-400/70 hover:bg-purple-500/20"
                        }`}
                      >
                        {generatingVideoIdx.has(i) ? <Loader2 size={11} className="animate-spin" /> : <Film size={11} />}
                        {scene.videoClipUrl ? "영상제거" : generatingVideoIdx.has(i) ? "생성중…" : "영상화"}
                      </button>
                    )}
                    <div className="flex-1" />
                    <button
                      onClick={(e) => { e.stopPropagation(); removeScene(i); }}
                      className="p-1 rounded-md hover:bg-red-500/20 transition-all"
                    >
                      <Trash2 size={11} className="text-ed-text-dim hover:text-red-400" />
                    </button>
                  </div>
                </div>
              );
            })}
          </div>
        </div>

        {/* ═══ RIGHT: Settings Panel ═══ */}
        <div className={`${mobileTab === "settings" ? "flex" : "hidden"} md:flex ${settingsPanelOpen ? "md:w-[24%]" : "md:w-[3%]"} w-full flex-col bg-ed-bg-panel transition-all duration-300 relative`}>
          {/* Toggle button - desktop only */}
          <button
            onClick={() => setSettingsPanelOpen((v) => !v)}
            className="hidden md:flex absolute -left-3 top-1/2 -translate-y-1/2 z-10 w-6 h-12 bg-ed-toggle-bg border border-ed-border rounded-l-lg items-center justify-center hover:bg-ed-surface-active transition-colors"
          >
            {settingsPanelOpen ? <ChevronRight size={14} className="text-ed-text-muted" /> : <ChevronLeft size={14} className="text-ed-text-muted" />}
          </button>
          {(settingsPanelOpen || mobileTab === "settings") ? (
          <>
          {currentScene ? (
            <div className="flex-1 overflow-y-auto scrollbar-hide p-4">
              <h3 className="text-[11px] font-semibold text-ed-text-muted mb-3 uppercase tracking-wider">
                장면 {selectedScene + 1} 편집
              </h3>
              <div className="space-y-4">
                {/* 씬 타입 토글 */}
                <div>
                  <label className="block text-[11px] text-ed-text-dim mb-2">씬 타입</label>
                  <div className="flex gap-2">
                    <button
                      onClick={() => currentScene.sceneType !== "motion" && toggleSceneType(selectedScene)}
                      className={`flex-1 flex items-center justify-center gap-1.5 py-2 rounded-lg text-xs font-medium transition-all ${
                        currentScene.sceneType === "motion"
                          ? "bg-accent/20 ring-1 ring-accent text-accent"
                          : "bg-ed-surface text-ed-text-muted hover:bg-ed-surface-active"
                      }`}
                    >
                      <Clapperboard size={13} />
                      모션
                    </button>
                    <button
                      onClick={() => currentScene.sceneType !== "image" && toggleSceneType(selectedScene)}
                      className={`flex-1 flex items-center justify-center gap-1.5 py-2 rounded-lg text-xs font-medium transition-all ${
                        currentScene.sceneType === "image"
                          ? "bg-blue-500/20 ring-1 ring-blue-500 text-blue-400"
                          : "bg-ed-surface text-ed-text-muted hover:bg-ed-surface-active"
                      }`}
                    >
                      <ImageIcon size={13} />
                      이미지
                    </button>
                  </div>
                </div>

                {/* 모션 스타일 선택 (모션 씬만) */}
                {currentScene.sceneType === "motion" && (
                  <div>
                    <div className="flex items-center justify-between mb-2">
                      <label className="text-[11px] text-ed-text-dim">모션 스타일</label>
                      <button
                        onClick={() => regenerateMotionData(selectedScene)}
                        disabled={regeneratingMotionIdx.has(selectedScene)}
                        className="flex items-center gap-1 px-2.5 py-1 text-[10px] font-medium bg-accent/15 hover:bg-accent/25 text-accent rounded-lg transition-all disabled:opacity-40"
                      >
                        {regeneratingMotionIdx.has(selectedScene) ? (
                          <Loader2 size={11} className="animate-spin" />
                        ) : (
                          <Wand2 size={11} />
                        )}
                        AI 재생성
                      </button>
                    </div>
                    <div className="grid grid-cols-3 gap-1.5">
                      {MOTION_STYLES.map((style) => (
                        <button
                          key={style.id}
                          onClick={() => updateScene(selectedScene, { motionStyle: style.id as MotionStyleId })}
                          className={`flex flex-col items-center gap-1 p-2 rounded-lg text-center transition-all ${
                            currentScene.motionStyle === style.id
                              ? "bg-accent/20 ring-1 ring-accent text-accent"
                              : "bg-ed-surface hover:bg-ed-surface-active text-ed-text-muted"
                          }`}
                        >
                          <span className="text-lg">{style.icon}</span>
                          <span className="text-[10px] font-medium leading-tight">{style.label}</span>
                        </button>
                      ))}
                    </div>
                    <p className="text-[10px] text-ed-text-dim mt-1.5">
                      {MOTION_STYLES.find((s) => s.id === currentScene.motionStyle)?.desc}
                    </p>
                    <p className="text-[9px] text-ed-text-dim/60 mt-1">
                      스타일 선택 후 &apos;AI 재생성&apos;을 누르면 대본에 맞는 데이터가 생성됩니다
                    </p>
                  </div>
                )}

                {/* 이미지 씬: 줌 방향 */}
                {currentScene.sceneType === "image" && (
                  <div>
                    <label className="block text-[11px] text-ed-text-dim mb-2">켄번스 줌</label>
                    <div className="flex gap-2">
                      {(["in", "out"] as const).map((dir) => (
                        <button
                          key={dir}
                          onClick={() => updateScene(selectedScene, { zoom: dir })}
                          className={`flex-1 py-2 rounded-lg text-xs font-medium transition-all ${
                            (currentScene.zoom ?? "in") === dir
                              ? "bg-blue-500/20 ring-1 ring-blue-500 text-blue-400"
                              : "bg-ed-surface text-ed-text-muted hover:bg-ed-surface-active"
                          }`}
                        >
                          {dir === "in" ? "🔍 줌인" : "🔎 줌아웃"}
                        </button>
                      ))}
                    </div>
                  </div>
                )}

                {/* TTS / 나레이션 */}
                <div className="rounded-xl bg-ed-surface border border-ed-border p-3 space-y-3">
                  <div className="flex items-center justify-between">
                    <label className="text-[11px] text-ed-text-dim flex items-center gap-1">
                      <Volume2 size={12} /> TTS 나레이션
                    </label>
                    <div className="flex items-center gap-1">
                      {currentScene.audioUrl && (
                        <button
                          onClick={() => playAudioPreview(selectedScene)}
                          className="p-1 rounded hover:bg-ed-surface-active transition-colors"
                          title="미리듣기"
                        >
                          {playingAudio === selectedScene ? (
                            <Pause size={12} className="text-green-400" />
                          ) : (
                            <Play size={12} className="text-green-400" />
                          )}
                        </button>
                      )}
                      <button
                        onClick={() => regenerateTTS(selectedScene)}
                        disabled={generatingTTSIdx.has(selectedScene)}
                        className="flex items-center gap-1 px-2 py-0.5 text-[10px] text-green-400 hover:bg-green-500/10 rounded transition-colors disabled:opacity-40"
                      >
                        {generatingTTSIdx.has(selectedScene) ? (
                          <Loader2 size={10} className="animate-spin" />
                        ) : (
                          <RefreshCw size={10} />
                        )}
                        {generatingTTSIdx.has(selectedScene) ? "생성 중…" : currentScene.audioUrl ? "재생성" : "TTS 생성"}
                      </button>
                    </div>
                  </div>
                  <textarea
                    value={currentScene.narration ?? currentScene.line}
                    onChange={(e) => updateScene(selectedScene, { narration: e.target.value })}
                    rows={2}
                    placeholder="나레이션 텍스트 (TTS로 변환됩니다)"
                    className="w-full bg-ed-surface border border-ed-border rounded-lg px-3 py-2 text-xs text-ed-text-muted resize-none focus:outline-none focus:border-green-500/50"
                  />
                  {showKoTranslation && koTranslations[selectedScene] && (
                    <p className="text-[10px] text-blue-400/70 mt-1 px-1">🇰🇷 {koTranslations[selectedScene]}</p>
                  )}
                  {currentScene.audioUrl && (
                    <div className="flex items-center gap-2 text-[10px] text-ed-text-dim">
                      <span className="px-1.5 py-0.5 rounded bg-green-500/10 text-green-400">
                        ✓ {currentScene.audioDuration?.toFixed(1)}초
                      </span>
                      <span className="truncate">{currentScene.audioUrl}</span>
                    </div>
                  )}
                </div>

                {/* 폰트 선택 (모션 씬만) */}
                {currentScene.sceneType === "motion" && (
                  <div>
                    <label className="block text-[11px] text-ed-text-dim mb-2">폰트</label>
                    <div className="grid grid-cols-3 gap-1.5">
                      {getFontsForLanguage(currentScene.language).map((font) => (
                        <button
                          key={font.id}
                          onClick={() => updateScene(selectedScene, { fontId: font.id })}
                          className={`px-2 py-2 rounded-lg text-center transition-all ${
                            (currentScene.fontId ?? (currentScene.language === "ja" ? "lineseed-jp" : "songmyeong")) === font.id
                              ? "bg-accent/20 ring-1 ring-accent text-accent"
                              : "bg-ed-surface hover:bg-ed-surface-active text-ed-text-muted"
                          }`}
                        >
                          <span className="block text-sm leading-tight" style={{ fontFamily: font.family }}>{currentScene.language === "ja" ? "あいう" : "가나다"}</span>
                          <span className="block text-[10px] mt-0.5 font-medium opacity-70">{font.label}</span>
                        </button>
                      ))}
                    </div>
                  </div>
                )}

                {/* 원본 대본 */}
                <div>
                  <label className="block text-[11px] text-ed-text-dim mb-1">원본 대본</label>
                  <textarea
                    value={currentScene.line}
                    onChange={(e) => updateScene(selectedScene, { line: e.target.value })}
                    rows={2}
                    className="w-full bg-ed-surface border border-ed-border rounded-lg px-3 py-2 text-[11px] text-ed-text-muted resize-none focus:outline-none focus:border-accent/50"
                  />
                </div>

                {/* 화면 문구 (모션 씬만) */}
                {currentScene.sceneType === "motion" && (
                  <>
                    <div>
                      <div className="flex items-center justify-between mb-1">
                        <label className="text-[11px] text-ed-text-dim">화면 표시 문구</label>
                        <button
                          onClick={() => refineWithAI(scenes, [selectedScene])}
                          disabled={isRefining}
                          className="flex items-center gap-1 px-2 py-0.5 text-[10px] text-purple-400 hover:bg-purple-500/10 rounded transition-colors disabled:opacity-40"
                        >
                          <Wand2 size={10} className={isRefining ? "animate-spin" : ""} />
                          {isRefining ? "생성 중…" : "AI 생성"}
                        </button>
                      </div>
                      <textarea
                        value={currentScene.displayText ?? ""}
                        onChange={(e) => updateScene(selectedScene, { displayText: e.target.value || undefined })}
                        rows={2}
                        placeholder="비워두면 대본에서 자동 추출"
                        className="w-full bg-ed-surface border border-ed-border rounded-lg px-3 py-2 text-xs text-ed-text resize-none focus:outline-none focus:border-accent/50"
                      />
                    </div>

                    {/* 보조 텍스트 */}
                    <div>
                      <label className="block text-[11px] text-ed-text-dim mb-1">보조 텍스트</label>
                      <input
                        type="text"
                        value={currentScene.subText ?? ""}
                        onChange={(e) => updateScene(selectedScene, { subText: e.target.value || undefined })}
                        placeholder="비워두면 없음"
                        className="w-full bg-ed-surface border border-ed-border rounded-lg px-3 py-2 text-xs text-ed-text focus:outline-none focus:border-accent/50"
                      />
                    </div>

                    {/* 출처 라벨 */}
                    <div>
                      <label className="block text-[11px] text-ed-text-dim mb-1">출처 라벨</label>
                      <input
                        type="text"
                        value={currentScene.sourceLabel ?? ""}
                        onChange={(e) => updateScene(selectedScene, { sourceLabel: e.target.value || undefined })}
                        placeholder="예: 노벨경제학상 수상자\n폴 크루그먼"
                        className="w-full bg-ed-surface border border-ed-border rounded-lg px-3 py-2 text-xs text-ed-text focus:outline-none focus:border-accent/50"
                      />
                      <p className="text-[10px] text-ed-text-faint mt-0.5">\n으로 줄바꿈. 비우면 표시 안 함</p>
                    </div>
                  </>
                )}

                {/* 모션 텍스트 크기 (모션만) */}
                {currentScene.sceneType === "motion" && (
                <div>
                  <div className="flex items-center justify-between mb-1">
                    <label className="text-[11px] text-ed-text-dim">모션 텍스트 크기</label>
                    <span className="text-[11px] text-ed-text-muted tabular-nums">
                      {currentScene.fontSize ?? 0 === 0 ? "자동" : `${currentScene.fontSize}px`}
                    </span>
                  </div>
                  <input
                    type="range"
                    min={0}
                    max={120}
                    step={2}
                    value={currentScene.fontSize ?? 0}
                    onChange={(e) => {
                      const v = Number(e.target.value);
                      updateScene(selectedScene, { fontSize: v === 0 ? undefined : v });
                    }}
                    className="w-full h-1.5 accent-accent bg-ed-surface-active rounded-full appearance-none cursor-pointer [&::-webkit-slider-thumb]:appearance-none [&::-webkit-slider-thumb]:w-3.5 [&::-webkit-slider-thumb]:h-3.5 [&::-webkit-slider-thumb]:rounded-full [&::-webkit-slider-thumb]:bg-accent [&::-webkit-slider-thumb]:shadow-md"
                  />
                  <p className="text-[10px] text-ed-text-faint mt-0.5">0 = 스타일 기본값</p>
                </div>
                )}

                {/* 자막 설정 (이미지 씬) - 드롭다운 */}
                {currentScene.sceneType === "image" && (
                  <div className="rounded-xl bg-ed-surface border border-ed-border overflow-hidden">
                    <button
                      onClick={() => setSubtitleOpen((p) => !p)}
                      className="w-full flex items-center justify-between px-3 py-2.5 text-[11px] text-ed-text-muted hover:text-ed-text-muted transition-colors"
                    >
                      <span className="flex items-center gap-1.5 font-medium">
                        <Sparkles size={12} /> 자막 설정
                      </span>
                      <ChevronDown size={14} className={`transition-transform ${subtitleOpen ? "rotate-180" : ""}`} />
                    </button>

                    {subtitleOpen && (
                    <div className="px-3 pb-3 space-y-3 border-t border-ed-surface pt-3">
                      {/* 위치 */}
                      <div>
                        <label className="block text-[10px] text-ed-text-dim mb-1.5">위치</label>
                        <div className="flex gap-1.5 mb-2">
                          {([
                            { label: "상단", x: 50, y: 10 },
                            { label: "중앙", x: 50, y: 50 },
                            { label: "하단", x: 50, y: 88 },
                          ]).map((preset) => {
                            const isActive =
                              (currentScene.subtitleX ?? 50) === preset.x &&
                              (currentScene.subtitleY ?? 88) === preset.y;
                            return (
                              <button
                                key={preset.label}
                                onClick={() => updateScene(selectedScene, { subtitleX: preset.x, subtitleY: preset.y })}
                                className={`flex-1 py-1.5 rounded-lg text-[10px] font-medium transition-all ${
                                  isActive
                                    ? "bg-accent/20 ring-1 ring-accent text-accent"
                                    : "bg-ed-surface text-ed-text-muted hover:bg-ed-surface-active"
                                }`}
                              >
                                {preset.label}
                              </button>
                            );
                          })}
                        </div>
                        <div className="space-y-2">
                          <div>
                            <div className="flex items-center justify-between mb-0.5">
                              <label className="text-[9px] text-ed-text-faint">X (가로)</label>
                              <span className="text-[9px] text-ed-text-dim tabular-nums">{currentScene.subtitleX ?? 50}%</span>
                            </div>
                            <input type="range" min={0} max={100} step={1} value={currentScene.subtitleX ?? 50}
                              onChange={(e) => updateScene(selectedScene, { subtitleX: Number(e.target.value) })}
                              className="w-full h-1 accent-accent bg-ed-surface-active rounded-full appearance-none cursor-pointer [&::-webkit-slider-thumb]:appearance-none [&::-webkit-slider-thumb]:w-3 [&::-webkit-slider-thumb]:h-3 [&::-webkit-slider-thumb]:rounded-full [&::-webkit-slider-thumb]:bg-accent [&::-webkit-slider-thumb]:shadow-md"
                            />
                          </div>
                          <div>
                            <div className="flex items-center justify-between mb-0.5">
                              <label className="text-[9px] text-ed-text-faint">Y (세로)</label>
                              <span className="text-[9px] text-ed-text-dim tabular-nums">{currentScene.subtitleY ?? 88}%</span>
                            </div>
                            <input type="range" min={0} max={100} step={1} value={currentScene.subtitleY ?? 88}
                              onChange={(e) => updateScene(selectedScene, { subtitleY: Number(e.target.value) })}
                              className="w-full h-1 accent-accent bg-ed-surface-active rounded-full appearance-none cursor-pointer [&::-webkit-slider-thumb]:appearance-none [&::-webkit-slider-thumb]:w-3 [&::-webkit-slider-thumb]:h-3 [&::-webkit-slider-thumb]:rounded-full [&::-webkit-slider-thumb]:bg-accent [&::-webkit-slider-thumb]:shadow-md"
                            />
                          </div>
                        </div>
                      </div>

                      {/* 크기 */}
                      <div>
                        <div className="flex items-center justify-between mb-1">
                          <label className="text-[10px] text-ed-text-dim">크기</label>
                          <span className="text-[10px] text-ed-text-muted tabular-nums">{currentScene.subtitleSize ?? 54}px</span>
                        </div>
                        <input type="range" min={18} max={80} step={2} value={currentScene.subtitleSize ?? 54}
                          onChange={(e) => updateScene(selectedScene, { subtitleSize: Number(e.target.value) })}
                          className="w-full h-1.5 accent-accent bg-ed-surface-active rounded-full appearance-none cursor-pointer [&::-webkit-slider-thumb]:appearance-none [&::-webkit-slider-thumb]:w-3.5 [&::-webkit-slider-thumb]:h-3.5 [&::-webkit-slider-thumb]:rounded-full [&::-webkit-slider-thumb]:bg-accent [&::-webkit-slider-thumb]:shadow-md"
                        />
                      </div>

                      {/* 폰트 */}
                      <div>
                        <label className="block text-[10px] text-ed-text-dim mb-1.5">폰트</label>
                        <div className="grid grid-cols-3 gap-1.5">
                          {getFontsForLanguage(currentScene.language).map((font) => (
                            <button key={font.id}
                              onClick={() => updateScene(selectedScene, { subtitleFont: font.id })}
                              className={`px-2 py-1.5 rounded-lg text-center transition-all ${
                                (currentScene.subtitleFont ?? (currentScene.language === "ja" ? "lineseed-jp" : "noto-sans")) === font.id
                                  ? "bg-accent/20 ring-1 ring-accent text-accent"
                                  : "bg-ed-surface hover:bg-ed-surface-active text-ed-text-muted"
                              }`}
                            >
                              <span className="block text-xs leading-tight" style={{ fontFamily: font.family }}>{currentScene.language === "ja" ? "あいう" : "가나다"}</span>
                              <span className="block text-[9px] mt-0.5 font-medium opacity-70">{font.label}</span>
                            </button>
                          ))}
                        </div>
                      </div>

                      {/* 배경 */}
                      <div>
                        <label className="block text-[10px] text-ed-text-dim mb-1.5">배경</label>
                        <div className="flex gap-1.5">
                          {([
                            { id: "none" as const, label: "없음" },
                            { id: "box" as const, label: "박스" },
                            { id: "fullbar" as const, label: "전체바" },
                          ]).map((opt) => (
                            <button key={opt.id}
                              onClick={() => updateScene(selectedScene, { subtitleBg: opt.id })}
                              className={`flex-1 py-2 rounded-lg text-[10px] font-medium transition-all ${
                                (currentScene.subtitleBg ?? "box") === opt.id
                                  ? "bg-accent/20 ring-1 ring-accent text-accent"
                                  : "bg-ed-surface text-ed-text-muted hover:bg-ed-surface-active"
                              }`}
                            >
                              {opt.label}
                            </button>
                          ))}
                        </div>
                      </div>

                      {/* 글자 색상 */}
                      <div>
                        <label className="block text-[10px] text-ed-text-dim mb-1.5">글자 색상</label>
                        <div className="flex items-center gap-1.5">
                          {["#ffffff", "#FFD600", "#FF5252", "#69F0AE", "#40C4FF"].map((c) => (
                            <button key={c}
                              onClick={() => updateScene(selectedScene, { subtitleColor: c })}
                              className={`w-6 h-6 rounded-md border-2 transition-all ${
                              (currentScene.subtitleColor ?? "#ffffff") === c
                                ? "border-accent scale-110 ring-2 ring-accent/30"
                                : "border-transparent hover:border-ed-text-dim"
                              }`}
                              style={{ backgroundColor: c }}
                            />
                          ))}
                          <div className="relative ml-1">
                            <input type="color" value={currentScene.subtitleColor ?? "#ffffff"}
                              onChange={(e) => updateScene(selectedScene, { subtitleColor: e.target.value })}
                              className="absolute inset-0 w-6 h-6 opacity-0 cursor-pointer"
                            />
                            <div className="w-6 h-6 rounded-md border-2 border-dashed border-ed-text-dim flex items-center justify-center text-ed-text-dim text-[10px]">+</div>
                          </div>
                        </div>
                      </div>

                      {/* 테두리 (획) on/off + 크기 */}
                      <div className="space-y-2">
                        <button
                          onClick={() => updateScene(selectedScene, { subtitleStroke: !(currentScene.subtitleStroke !== false) })}
                          className={`w-full flex items-center justify-between px-3 py-2 rounded-lg text-[10px] font-medium transition-all ${
                            currentScene.subtitleStroke !== false
                              ? "bg-ed-surface-active text-ed-text-muted"
                              : "bg-ed-surface text-ed-text-dim"
                          }`}
                        >
                          <span>테두리 (획/외곽선)</span>
                          <span className={`px-2 py-0.5 rounded-md text-[9px] font-bold ${
                            currentScene.subtitleStroke !== false
                              ? "bg-accent/20 text-accent"
                              : "bg-ed-surface-active text-ed-text-dim"
                          }`}>
                            {currentScene.subtitleStroke !== false ? "ON" : "OFF"}
                          </span>
                        </button>
                        {currentScene.subtitleStroke !== false && (
                          <div>
                            <div className="flex items-center justify-between mb-0.5">
                              <label className="text-[9px] text-ed-text-faint">획 두께</label>
                              <span className="text-[9px] text-ed-text-dim tabular-nums">{currentScene.subtitleStrokeWidth ?? Math.max(1, Math.round((currentScene.subtitleSize ?? 54) / 16))}px</span>
                            </div>
                            <input type="range" min={1} max={10} step={1}
                              value={currentScene.subtitleStrokeWidth ?? Math.max(1, Math.round((currentScene.subtitleSize ?? 54) / 16))}
                              onChange={(e) => updateScene(selectedScene, { subtitleStrokeWidth: Number(e.target.value) })}
                              className="w-full h-1 accent-accent bg-ed-surface-active rounded-full appearance-none cursor-pointer [&::-webkit-slider-thumb]:appearance-none [&::-webkit-slider-thumb]:w-3 [&::-webkit-slider-thumb]:h-3 [&::-webkit-slider-thumb]:rounded-full [&::-webkit-slider-thumb]:bg-accent [&::-webkit-slider-thumb]:shadow-md"
                            />
                          </div>
                        )}
                      </div>
                    </div>
                    )}
                  </div>
                )}

                {/* 페이드 인/아웃 토글 */}
                <div>
                  <button
                    onClick={() => updateScene(selectedScene, { fadeEnabled: !currentScene.fadeEnabled })}
                    className={`w-full flex items-center justify-between px-3 py-2.5 rounded-xl text-xs font-medium transition-all ${
                      currentScene.fadeEnabled
                        ? "bg-ed-surface-active text-ed-text-muted"
                        : "bg-ed-surface text-ed-text-dim"
                    }`}
                  >
                    <span>페이드 인/아웃</span>
                    <span className={`px-2 py-0.5 rounded-md text-[10px] font-bold ${
                      currentScene.fadeEnabled
                        ? "bg-accent/20 text-accent"
                        : "bg-ed-surface-active text-ed-text-dim"
                    }`}>
                      {currentScene.fadeEnabled ? "ON" : "OFF"}
                    </span>
                  </button>
                </div>

                {/* Highlight color (모션만) */}
                {currentScene.sceneType === "motion" && (
                  <div>
                    <label className="block text-[11px] text-ed-text-dim mb-1.5">하이라이트 색상</label>
                    <div className="flex items-center gap-1.5">
                      {["#FFD600", "#FF5252", "#69F0AE", "#40C4FF", "#FF80AB", "#B388FF", "#FFFFFF"].map(
                        (color) => (
                          <button
                            key={color}
                            onClick={() => updateScene(selectedScene, { highlightColor: color })}
                            className={`w-7 h-7 rounded-lg border-2 transition-all ${
                            (currentScene.highlightColor ?? "#FFD600") === color
                              ? "border-accent scale-110 ring-2 ring-accent/30"
                              : "border-transparent hover:border-ed-text-dim"
                            }`}
                            style={{ backgroundColor: color }}
                          />
                        ),
                      )}
                      <div className="relative ml-1">
                        <input
                          type="color"
                          value={currentScene.highlightColor ?? "#FFD600"}
                          onChange={(e) => updateScene(selectedScene, { highlightColor: e.target.value })}
                          className="absolute inset-0 w-7 h-7 opacity-0 cursor-pointer"
                        />
                        <div className="w-7 h-7 rounded-lg border-2 border-dashed border-ed-text-dim flex items-center justify-center text-ed-text-dim text-xs" title="커스텀 색상">+</div>
                      </div>
                    </div>
                  </div>
                )}

                {/* Keywords edit (모션만) */}
                {currentScene.sceneType === "motion" && (
                  <div>
                    <label className="block text-[11px] text-ed-text-dim mb-1">하이라이트 키워드</label>
                    <input
                      type="text"
                      value={currentScene.keywords.join(", ")}
                      onChange={(e) => {
                        const kws = e.target.value.split(",").map((s) => s.trim()).filter(Boolean);
                        updateScene(selectedScene, { keywords: kws });
                      }}
                      placeholder="쉼표로 구분"
                      className="w-full bg-ed-surface border border-ed-border rounded-lg px-3 py-2 text-xs text-ed-text focus:outline-none focus:border-accent/50"
                    />
                  </div>
                )}

                {/* 효과음 (모션 씬만) */}
                {currentScene.sceneType === "motion" && (
                  <div className="rounded-xl bg-ed-surface border border-ed-border p-3 space-y-2">
                    <div className="flex items-center justify-between">
                      <label className="text-[11px] text-ed-text-dim flex items-center gap-1"><Music size={11} /> 효과음</label>
                      {currentScene.sfxUrl ? (
                        <button
                          onClick={() => updateScene(selectedScene, { sfxUrl: undefined })}
                          className="text-[10px] text-red-400 hover:text-red-500 transition-colors"
                        >
                          제거
                        </button>
                      ) : (
                        <button
                          onClick={() => generateSfx(selectedScene)}
                          disabled={generatingSfx}
                          className="flex items-center gap-1 px-2 py-0.5 text-[10px] text-purple-400 hover:bg-purple-500/10 rounded transition-colors disabled:opacity-40"
                        >
                          {generatingSfx ? <Loader2 size={10} className="animate-spin" /> : <Sparkles size={10} />}
                          {generatingSfx ? "생성 중…" : "자동 생성"}
                        </button>
                      )}
                    </div>
                    {currentScene.sfxUrl && (
                      <div className="space-y-1.5">
                        <div className="flex items-center gap-2">
                          <audio src={currentScene.sfxUrl} controls className="h-7 flex-1" style={{ minWidth: 0 }} />
                          <button
                            onClick={() => generateSfx(selectedScene)}
                            disabled={generatingSfx}
                            className="p-1 text-ed-text-dim hover:text-accent rounded transition-colors disabled:opacity-40"
                            title="다시 생성"
                          >
                            {generatingSfx ? <Loader2 size={12} className="animate-spin" /> : <RefreshCw size={12} />}
                          </button>
                        </div>
                        <div>
                          <label className="text-[10px] text-ed-text-faint">볼륨: {Math.round((currentScene.sfxVolume ?? 0.15) * 100)}%</label>
                          <input
                            type="range" min={0} max={1} step={0.05}
                            value={currentScene.sfxVolume ?? 0.15}
                            onChange={(e) => updateScene(selectedScene, { sfxVolume: Number(e.target.value) })}
                            className="w-full accent-purple-500"
                          />
                        </div>
                      </div>
                    )}
                  </div>
                )}

                {/* 배경 이미지 */}
                <div className="rounded-xl bg-ed-surface border border-ed-border p-3 space-y-2.5">
                  <div className="flex items-center justify-between">
                    <label className="text-[11px] text-ed-text-dim">배경 이미지</label>
                    <button
                      onClick={() => regenerateImage(selectedScene, currentScene.imagePrompt || undefined)}
                      disabled={generatingImageIdx.has(selectedScene)}
                      className="flex items-center gap-1 px-2 py-0.5 text-[10px] text-blue-400 hover:bg-blue-500/10 rounded transition-colors disabled:opacity-40"
                    >
                      {generatingImageIdx.has(selectedScene) ? (
                        <Loader2 size={10} className="animate-spin" />
                      ) : (
                        <ImagePlus size={10} />
                      )}
                      {generatingImageIdx.has(selectedScene) ? "생성 중…" : "재생성"}
                    </button>
                  </div>
                  {currentScene.mainImage && (
                    <div className="rounded-lg overflow-hidden border border-ed-border">
                      <img src={currentScene.mainImage} alt="배경" className="w-full h-24 object-cover" />
                    </div>
                  )}
                  <div className="text-[9px] text-ed-text-faint px-1 py-1 rounded bg-ed-surface-active/30 flex flex-wrap gap-x-3 gap-y-0.5">
                    <span>모델: <b className="text-ed-text-muted">{projectStyle?.imageModel || "기본(google:4@3)"}</b></span>
                    {projectStyle?.styleDescription && <span className="text-green-400">✓ 스타일 분석 적용</span>}
                    {projectStyle?.characterRefImage && <span className="text-blue-400">✓ 레퍼런스</span>}
                    {!projectStyle?.styleDescription && !projectStyle?.styleImage && !projectStyle?.characterRefImage && (
                      <span className="text-yellow-400">⚠ 스타일 미설정</span>
                    )}
                  </div>
                  <div>
                    <label className="block text-[9px] text-ed-text-faint mb-1">이미지 프롬프트</label>
                    <textarea
                      value={currentScene.imagePrompt ?? ""}
                      onChange={(e) => updateScene(selectedScene, { imagePrompt: e.target.value || undefined })}
                      rows={3}
                      placeholder="비워두면 대본 기반 자동 생성. 프롬프트를 직접 입력하고 재생성 버튼을 누르세요."
                      className="w-full bg-ed-surface border border-ed-border rounded-lg px-3 py-2 text-[11px] text-ed-text-muted resize-none focus:outline-none focus:border-blue-500/50 placeholder:text-ed-text-faint"
                    />
                  </div>
                  <input
                    type="text"
                    value={currentScene.mainImage}
                    onChange={(e) => updateScene(selectedScene, { mainImage: e.target.value, backgroundImage: e.target.value })}
                    placeholder="이미지 URL 직접 입력"
                    className="w-full bg-ed-surface border border-ed-border rounded-lg px-3 py-2 text-[10px] text-ed-text-muted focus:outline-none focus:border-accent/50"
                  />

                  {currentScene.sceneType === "image" && (
                    <div className="flex items-center justify-between pt-2 border-t border-ed-surface">
                      <div className="flex items-center gap-2">
                        <Film size={12} className="text-purple-400" />
                        <span className="text-[11px] text-ed-text-muted">
                          {currentScene.videoClipUrl ? "영상 클립 적용됨" : "AI 영상화"}
                        </span>
                      </div>
                      <div className="flex items-center gap-1">
                        {currentScene.videoClipUrl && (
                          <button
                            onClick={() => removeVideoClip(selectedScene)}
                            className="px-2 py-0.5 text-[10px] text-red-400 hover:bg-red-500/10 rounded transition-colors"
                          >
                            제거
                          </button>
                        )}
                        <button
                          onClick={() => generateVideoClip(selectedScene)}
                          disabled={generatingVideoIdx.has(selectedScene) || !currentScene.mainImage}
                          className="flex items-center gap-1 px-2 py-0.5 text-[10px] text-purple-400 hover:bg-purple-500/10 rounded transition-colors disabled:opacity-40"
                        >
                          {generatingVideoIdx.has(selectedScene) ? (
                            <Loader2 size={10} className="animate-spin" />
                          ) : (
                            <Film size={10} />
                          )}
                          {generatingVideoIdx.has(selectedScene) ? "생성 중…" : currentScene.videoClipUrl ? "재생성" : "영상화"}
                        </button>
                      </div>
                    </div>
                  )}
                </div>

                {/* Per-scene export */}
                <button
                  onClick={() => handleExportScene(selectedScene)}
                  disabled={isRendering}
                  className="w-full flex items-center justify-center gap-2 py-2.5 text-xs font-medium bg-ed-surface border border-ed-border rounded-xl hover:bg-ed-surface-active transition-colors disabled:opacity-40"
                >
                  {isRendering ? (
                    <>
                      <RotateCcw size={13} className="animate-spin" />
                      렌더링 중
                    </>
                  ) : (
                    <>
                      <Film size={13} />
                      이 장면만 내보내기
                    </>
                  )}
                </button>
              </div>
            </div>
          ) : (
            <div className="flex-1 flex items-center justify-center p-6">
              <p className="text-[11px] text-ed-text-faint text-center">왼쪽 목록에서<br />장면을 선택하세요</p>
            </div>
          )}
          </>
          ) : (
            <div className="flex-1" />
          )}
        </div>

      </div>
      </div>

      <RenderConfirmDialog
        open={confirmDialog.open}
        sceneCount={confirmDialog.sceneCount}
        estimatedSeconds={estimateRenderSeconds(confirmDialog.sceneCount)}
        onConfirm={handleConfirmRender}
        onCancel={handleCancelRender}
      />
    </div>
  );
}
